In [38]:
import numpy as np
from sklearn import datasets
import pandas as pd
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib.artist'

In [18]:
iris = datasets.load_iris()
X = pd.DataFrame(iris.data)
y = iris.target

m, n = X.shape
print(m, n)

150 4


In [19]:
means = X.mean()
means

0    5.843333
1    3.054000
2    3.758667
3    1.198667
dtype: float64

In [20]:
# def mean_normalization(x):
#     for i in range(len(x)):
#         x[i] = x[i] - means[i]
#     return x
    
# XX = X.apply(mean_normalization, axis='columns')

XX = X - means

In [21]:
sigma = 1/(m-1) * np.dot(np.transpose(XX), XX)

In [22]:
sigma

array([[ 0.68569351, -0.03926846,  1.27368233,  0.5169038 ],
       [-0.03926846,  0.18800403, -0.32171275, -0.11798121],
       [ 1.27368233, -0.32171275,  3.11317942,  1.29638747],
       [ 0.5169038 , -0.11798121,  1.29638747,  0.58241432]])

In [23]:
cov_mat = np.cov([XX.iloc[0,:],XX.iloc[1,:],XX.iloc[2,:]], XX.iloc[3, :])
print(cov_mat)

[[1.32431896 1.0863523  1.21380785 1.06647452]
 [1.0863523  0.90421896 1.00584119 0.88184119]
 [1.21380785 1.00584119 1.13663007 1.00596341]
 [1.06647452 0.88184119 1.00596341 0.89529674]]


In [24]:
v, m = np.linalg.eig(sigma)

In [25]:
v

array([4.22484077, 0.24224357, 0.07852391, 0.02368303])

In [26]:
m_pca = m[:, :2]

In [28]:
new_X = np.dot(XX, m_pca)

In [29]:
sns.scatterplot(x = new_X[:, 0], y = new_X[:, 1], hue = y)

NameError: name 'sns' is not defined

In [40]:
from sklearn import decomposition

In [41]:
pca = decomposition.PCA(n_components=2)
XXX = pca.fit_transform(X)
pca.get_covariance()

array([[ 0.67919741, -0.03258618,  1.27066452,  0.5321852 ],
       [-0.03258618,  0.18113034, -0.31863564, -0.13363564],
       [ 1.27066452, -0.31863564,  3.11934547,  1.28541527],
       [ 0.5321852 , -0.13363564,  1.28541527,  0.58961806]])

In [ ]:
sns.scatterplot(x = XXX[:, 0], y = XXX[:, 1], hue = y)

In [ ]:
XXX

In [ ]:
new_X

In [ ]:
from mpl_toolkits.mplot3d import Axes3D

In [ ]:
fig = plt.figure(1, figsize=(4, 3))
plt.clf()
ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)

plt.cla()

ax.scatter(X.iloc[:, 0], X.iloc[:, 1], X.iloc[:, 2], c=y, cmap=plt.cm.nipy_spectral,
           edgecolor='k')

ax.w_xaxis.set_ticklabels([])
ax.w_yaxis.set_ticklabels([])
ax.w_zaxis.set_ticklabels([])

plt.show()